[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
libcamera = { git = "https://github.com/lit-robotics/libcamera-rs" }
opencv = { version = "0.94.1", features = ["clang-runtime"] }

[workspace.lints.rust]